export const slides = [
  {
    image: "/hero-1.jpeg",
    caption: "Slide 1",
    text: "Find creative spaces in",
    highlight: "Lagos, Nigeria",
  },
  {
    image: "/hero-2.jpeg",
    caption: "Slide 2",
    text: "Discover curated spaces for",
    highlight: "Memorable Events",
  },
  {
    image: "/hero-3.jpeg",
    caption: "Slide 3",
    text: "Browse and scout",
    highlight: "200+ locations",
    afterText: "with real reviews",
  },
  {
    image: "/hero-4.jpeg",
    caption: "Slide 4",
    text: "Find creative spaces in",
    highlight: "Lagos, Nigeria",
  },
];

export const explore = [
  {
    image: "/ikoyi-link-bridge.jpeg",
    name: "Ikoyi",
    locationNumber: 7,
  },
  {
    image: "/yaba.jpeg",
    name: "Yaba",
    locationNumber: 5,
  },
  {
    image: "/ikeja.png",
    name: "Ikeja",
    locationNumber: 10,
  },
  {
    image: "/lekki-bridge.jpeg",
    name: "Lekki",
    locationNumber: 25,
  },
];

export const spaces = [
  {
    image: "/party.jpeg",
    name: "Party",
    spaceNumber: 10,
  },
  {
    image: "/content.jpeg",
    name: "Content",
    spaceNumber: 5,
  },
  {
    image: "/podcast.jpeg",
    name: "Podcasts",
    spaceNumber: 10,
  },
  {
    image: "/meetings.jpeg",
    name: "Meetings",
    spaceNumber: 25,
  },
  {
    image: "/popup.png",
    name: "Popup",
    spaceNumber: 25,
  },
];

export const membershipPlans = [
  {
    id: 1,
    title: "STANDARD",
    price: "₦100,000",
    bgColor: "bg-[#FDF1C3]",
    textColor: "text-[#9C7C00]",
    benefits: [
      "10 hours/month of studio time",
      "10% discount on add-ons",
      "Free use of standard studio props",
    ],
    footer: "- Exclusive Shanty Studios; Twelve’s Place -",
    footerTextColor: "text-[#0155AD]",
  },
  {
    id: 2,
    title: "PROFESSIONAL",
    price: "₦200,000",
    bgColor: "bg-[#001F3F]",
    textColor: "text-white",
    benefits: [
      "20 hours/month of studio time",
      "20% discount on add-ons",
      "Free use of standard studio props",
      "Assistance setting up",
    ],
    footer: "- Exclusive Shanty Studios; Twelve’s Place -",
    footerTextColor: "text-[#0155AD]",
  },
  {
    id: 3,
    title: "ELITE",
    price: "₦300,000",
    bgColor: "bg-[#68303A]",
    textColor: "text-[#FFF8F9]",
    benefits: [
      "40 hours/month of studio time",
      "30% discount on add-ons",
      "Free use of standard studio props",
      "Assistance setting up and standby staff",
    ],
    footer: "- Access to all listings -",
    footerTextColor: "text-[#001224]",
  },
];

export const submenuItems: Record<string, string[]> = {
  Locations: [
    "Yaba",
    "Lekki",
    "Ebute Metta",
    "Ikorodu",
    "Ikoyi",
    "Victoria Island",
  ],
  Activities: [
    "Photoshoot",
    "Videoshoot",
    "Party",
    "Dinner",
    "Large Gathering",
    "Training",
    "See All",
  ],
  "Space Types": [
    "Content House",
    "Photo Studio",
    "Podcast Room",
    "Party Room",
  ],
  Amenities: [
    "Free WiFi",
    "Lightening",
    "Abstract Props",
    "Wheelchair Accessible",
    "Graphic Walls",
  ],
};

export const listings = [
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-1.jpeg",
      "/listing-2.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: [
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-3.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-3.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-4.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: [
      "/listing-4.jpeg",
      "/listing-2.jpeg",
      "/listing-1.jpeg",
      "/listing-1.jpeg",
    ],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
];

export const profileListings = [
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
];

export const bookingItems = [
  { icon: "/sun.svg", text: "Lighting Equipments" },
  { icon: "/buildings-2.svg", text: "Changing Room" },
  { icon: "/wifi.svg", text: "WiFi" },
  { icon: "/video-play.svg", text: "Video Equipment" },
  { icon: "/winter.svg", text: "Air Conditioning" },
];

export const addOns = [
  {
    id: 1,
    title: "Camera",
    description: "2016 Sony camera for photography",
    price: "₦45,000",
    image: "/camera.jpeg",
  },
  {
    id: 2,
    title: "Tripod",
    description: "Stable tripod for professional shoots",
    price: "₦10,000",
    image: "/camera.jpeg",
  },
  {
    id: 3,
    title: "Lighting Kit",
    description: "Essential lighting kit for indoor shoots",
    price: "₦25,000",
    image: "/camera.jpeg",
  },
  {
    id: 4,
    title: "Microphone",
    description: "High-quality microphone for sound recording",
    price: "₦15,000",
    image: "/camera.jpeg",
  },
  {
    id: 5,
    title: "Drone",
    description: "DJI Drone for aerial photography",
    price: "₦150,000",
    image: "/camera.jpeg",
  },
];
